name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
    - name: Write .env
      run: |
        set -e
        cat > .env <<EOF
        GOOGLE_SERVICE_ACCOUNT_MAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_MAIL }}
        GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
        EOF

    - name: test
      run: npm run test
    - name: build
      run: npm run build
