name: Deploy retreat config
on:
  workflow_dispatch:
#  schedule:
#    - cron: "1 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout virtual-office-scheduler
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Write .env
        run: |
          set -e
          cat > .env <<EOF
          GOOGLE_SPREADSHEET_ID=${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_MAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_MAIL }}
          GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
          SCHEDULE_SHEET_NAME=Schedule
          MEETINGS_SHEET_NAME=Meetings
          CONFLUENCE_BASE_URL=${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_USER=${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_PASSWORD=${{ secrets.CONFLUENCE_PASSWORD }}
          CONFLUENCE_SPACE_KEY=SR
          CONFLUENCE_PARENT_PAGE_ID=444237186
          CONFLUENCE_TEMPLATE_PAGE_ID=424940306
          VIRTUAL_OFFICE_BASE_URL=${{ secrets.VIRTUAL_OFFICE_BASE_URL }}
          NEWBIE_VIRTUAL_OFFICE_BASE_URL=${{ secrets.NEWBIE_VIRTUAL_OFFICE_BASE_URL }}
          VIRTUAL_OFFICE_USERNAME=${{ secrets.VIRTUAL_OFFICE_USERNAME }}
          VIRTUAL_OFFICE_PASSWORD=${{ secrets.VIRTUAL_OFFICE_PASSWORD }}
          ENABLE_ROOM_JOIN_MINUTES_BEFORE_START=15
          EOF

      - name: Deploy retreat schedule
        run: |
          npm install
          npm run start:scheduleSessions
